- name: Install github3.py python package
  pip:
    name: github3.py

- name: Get nvm latest tag
  when: INSTALL_NVM | bool
  github_release:
    user: nvm-sh
    repo: nvm
    action: latest_release
  register: nvm_latest

- name: Clone nvm
  when: INSTALL_NVM | bool
  git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "{{ OE_HOME }}/.nvm"
    version: "{{ nvm_latest['tag'] }}"

- name: Install nvm
  when: INSTALL_NVM | bool
  script: "{{ OE_HOME }}/.nvm/install.sh"
  args:
    executable: /bin/bash
