- hosts: ubuntu
  tasks:
    - name: install dependent library
      become: yes
      apt:
        name:
          - python3-venv
          - python3-wheel
          - libxslt-dev
          - libzip-dev
          - libldap2-dev
          - libsasl2-dev
          - python3-setuptools
          - node-less
          - libjpeg-dev
          - gdebi
          - python3-virtualenv
          - git
          - python3
          - python3-pip
          - build-essential
          - wget
          - make
          - vim
          - python3-dev
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - curl
          - llvm
          - libncurses5-dev
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libffi-dev
          - liblzma-dev
          - python-openssl
          - libxml2-dev
          - libxslt1-dev
          - libjpeg62-dev
          - vim-gtk3
          - pipenv
          - silversearcher-ag
          - exuberant-ctags
          - figlet
          - tox
          - net-tools
          - htop
        state: present
        autoclean: yes
