- name: Clone ranger
  when: INSTALL_RANGER | bool
  ansible.builtin.git:
    repo: https://github.com/ranger/ranger.git
    dest: /tmp/ranger
    version: master

- name: Install ranger
  when: INSTALL_RANGER | bool
  become: true
  ansible.builtin.make:
    chdir: /tmp/ranger
    target: install
