- name: Clone ranger
  when: INSTALL_RANGER | bool
  git:
    repo: https://github.com/ranger/ranger.git
    dest: /tmp/ranger
    version: master

- name: Install ranger
  when: INSTALL_RANGER | bool
  become: true
  make:
    chdir: /tmp/ranger
    target: install
