- name: Clone fzf
  when: INSTALL_FZF | bool
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ OE_HOME }}/.fzf"
    depth: 1
    version: master

#- name: Install FZF
 # when: INSTALL_FZF | bool
  #script: "{{ OE_HOME }}/.fzf/install"
  #args:
   # executable: /bin/bash
    
- name: Install FZF
  when: INSTALL_FZF | bool
  expect:
    command: "{{ OE_HOME }}/.fzf/install"
    responses:
      'First Question in the prompt' : 'y'
      'Second Question in the prompt' : 'y'
      'Thired Question in the prompt' : 'y'
