- name: Clone fzf
  when: INSTALL_FZF | bool
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ OE_HOME }}/.fzf"
    depth: 1
    version: master
    
- name: Install python pexpect
  when: INSTALL_FZF | bool
  become: true
  apt:
    name:
      python-pexpect

- name: Install FZF
  when: INSTALL_FZF | bool
  expect:
    command: "{{ OE_HOME }}/.fzf/install"
    responses:
      'Do you want to enable fuzzy auto-completion\? \(\[y\]\/n\) ': 'y'
      'Do you want to enable key bindings\? \(\[y\]\/n\) ': 'y'
      'Do you want to update your shell configuration files\? \(\[y\]\/n\) ': 'y'
    echo: yes
