- name: Clone fzf
  when: INSTALL_FZF | bool
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ OE_HOME }}/.fzf"
    depth: 1
    version: master

- name: Install FZF
  when: INSTALL_FZF | bool
  ansible.builtin.script: "{{ OE_HOME }}/.fzf/install"
  args:
    executable: /bin/bash
