- name: Download pyenv-installer
  when: INSTALL_PYENV | bool
  get_url:
    url: https://raw.github.com/yyuu/pyenv-installer/master/bin/pyenv-installer
    dest: "/tmp/pyenv-installer.sh"
    mode: 0755
    group: "{{ OE_USER }}"
    owner: "{{ OE_USER }}"

- name: (Check) .pyenv exists
  when: INSTALL_PYENV | bool
  stat:
    path: "{{ OE_HOME }}/.pyenv"
  register: pyenv_exists
  

- name: (Output) .pyenv exists
  when: INSTALL_PYENV | bool and pyenv_exists.stat.exists | bool
  debug: 
    msg: 
      - '.pyenv already exists, install command skip!'

- name: Install PYENV
  when: INSTALL_PYENV | bool and not pyenv_exists.stat.exists | bool
  script: /tmp/pyenv-installer.sh
  args:
    executable: /bin/bash

- name: (Check) .bashrc exists
  when: INSTALL_PYENV | bool
  stat:
    path: "{{ OE_HOME }}/.bashrc"
  register: bashrc_exists

- name: Setup .bashrc
  when: INSTALL_PYENV | bool and bashrc_exists.stat.exists | bool
  shell: |
      echo 'export PYENV_ROOT="{{ OE_HOME }}/.pyenv"' >> {{ OE_HOME }}/.bashrc
      echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> {{ OE_HOME }}/.bashrc
      echo 'eval "$(pyenv init -)"' >> {{ OE_HOME }}/.bashrc
      echo 'export PYENV_VIRTUALENV_DISABLE_PROMPT=1' >> {{ OE_HOME }}/.bashrc
  args:
    executable: /bin/bash

- name: (Check) .profile exists
  when: INSTALL_PYENV | bool
  stat:
    path: "{{ OE_HOME }}/.profile"
  register: profile_exists

- name: Setup .bashrc
  when: INSTALL_PYENV | bool and profile_exists.stat.exists | bool
  shell: |
      echo 'export PYENV_ROOT="{{ OE_HOME }}/.pyenv"' >> {{ OE_HOME }}/.profile
      echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> {{ OE_HOME }}/.profile
      echo 'eval "$(pyenv init -)"' >> {{ OE_HOME }}/.profile
      echo 'export PYENV_VIRTUALENV_DISABLE_PROMPT=1' >> {{ OE_HOME }}/.profile
  args:
    executable: /bin/bash

- name: (Check) .bash_profile exists
  when: INSTALL_PYENV | bool
  stat:
    path: "{{ OE_HOME }}/.bash_profile"
  register: bash_profile_exists

- name: Setup .bash_profile exists
  when: INSTALL_PYENV | bool and bash_profile_exists.stat.exists | bool
  shell: |
      echo 'export PYENV_ROOT="{{ OE_HOME }}/.pyenv"' >> {{ OE_HOME }}/.bash_profile
      echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> {{ OE_HOME }}/.bash_profile
      echo 'eval "$(pyenv init -)"' >> {{ OE_HOME }}/.bash_profile
      echo 'export PYENV_VIRTUALENV_DISABLE_PROMPT=1' >> {{ OE_HOME }}/.bash_profile
  args:
    executable: /bin/bash

- name: (Check) .zshrc exists
  when: INSTALL_PYENV | bool
  stat:
    path: "{{ OE_HOME }}/.zshrc"
  register: zshrc_exists

- name: Setup .zshrc exists
  when: INSTALL_PYENV | bool and zshrc_exists.stat.exists | bool
  shell: |
      echo 'export PYENV_ROOT="{{ OE_HOME }}/.pyenv"' >> {{ OE_HOME }}/.zshrc
      echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> {{ OE_HOME }}/.zshrc
      echo 'eval "$(pyenv init -)"' >> {{ OE_HOME }}/.zshrc
      echo 'export PYENV_VIRTUALENV_DISABLE_PROMPT=1' >> {{ OE_HOME }}/.zshrc
  args:
    executable: /bin/bash
