- name: (Check) if LSD is installed
  when: INSTALL_LSD | bool
  command: dpkg-query -W lsd
  register: check_lsd_deb
  failed_when: check_lsd_deb.rc > 1
  changed_when: check_lsd_deb.rc == 1

- name: (Check) system amd or arm
  when: INSTALL_LSD | bool
  command: dpkg --print-architecture
  register: system_structure
  failed_when: system_structure.stdout not in ["arm64", "amd64"]

- name: Download lsd.deb
  when: INSTALL_LSD | bool
  get_url:
    url: "https://github.com/Peltoche/lsd/releases/download/0.22.0/lsd_0.22.0_{{ system_structure.stdout }}.deb"
    dest: "/tmp/lsd_0.22.0_{{ system_structure.stdout }}.deb"
    mode: 0644
    group: "{{ OE_USER }}"
    owner: "{{ OE_USER }}"

- name: Install lsd.deb
  when: INSTALL_LSD | bool
  become: true
  apt: deb="/tmp/lsd_0.22.0_{{ system_structure.stdout }}.deb"
  
- name: Insert lsd [Alias] Block
  when: INSTALL_LSD | bool
  shell:
    cmd: |
      BASH_PATH={{ OE_HOME }}/.bashrc
      cat << EOF >> $BASH_PATH
      # [lsd]
      alias ls='lsd'
      alias l='ls -l'
      alias la='ls -a'
      alias lla='ls -la'
      alias lt='ls --tree'
      EOF
  args:
    executable: /bin/bash
